# Generated by Django 3.2.8 on 2021-11-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='order_lineitem_id',
            field=models.CharField(editable=False, max_length=50),
        ),
    ]
